In [2]:
%pip install numpy


In [3]:
import numpy as np

In [41]:
ls = [62, 42, 85]  # Creating a Python list
print(type(ls))  # Checking and printing the type of 'ls'

arr = np.array(ls)  # Converting the list into a NumPy array
print(type(arr))  # Checking and printing the type of 'arr'

<class 'list'>
<class 'numpy.ndarray'>


In [5]:
arr1= np.array([1,2,3,4,5,6])
print(type(arr1))

<class 'numpy.ndarray'>


In [ ]:
#arange(start, stop, step)- It creates an array with values in a given range with a specific step.
arr2= np.arange(1,25)
arr2 #1D array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [ ]:
# zeros(rows,columns) - Creates an array filled with zeros
arr3= np.zeros((2,5))
arr3

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
# ones(rows,columns) - Creates an array filled with ones
arr4= np.ones((5,3))
arr4

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [9]:
arr5= np.arange(1,25,2)
arr5

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23])

In [ ]:
#linspace(start, stop, num) - Generates num equally spaced values between start and stop.
arr6= np.linspace(1,2,5)
arr6

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [ ]:
# Reshape the array in 2D
arr7=np.arange(0,30).reshape(10,3)
arr7

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29]])

In [12]:
# Slicing a 1D array
arr1d = np.array([10, 20, 30, 40, 50, 60, 70])

# Basic slicing
print(arr1d[1:5])    # Output: [20 30 40 50]
print(arr1d[:4])     # Output: [10 20 30 40]
print(arr1d[3:])     # Output: [40 50 60 70]
print(arr1d[::2])    # Output: [10 30 50 70] (Every second element)
print(arr1d[::-1])   # Output: [70 60 50 40 30 20 10] (Reverse array)


[20 30 40 50]
[10 20 30 40]
[40 50 60 70]
[10 30 50 70]
[70 60 50 40 30 20 10]


In [40]:
# Slicing a 2D array
arr2d = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12]])

# Extract a subarray
print(arr2d[0:2, 1:3])

# Extract first row
print(arr2d[0, :])

# Extract first column
print(arr2d[:, 0])

# Extract last two rows
print(arr2d[-2:, :])


[[2 3]
 [6 7]]
[1 2 3 4]
[1 5 9]
[[ 5  6  7  8]
 [ 9 10 11 12]]


In [39]:
# Slicing a 3D array
arr3d = np.array([[[1, 2, 3], [4, 5, 6]],
                  [[7, 8, 9], [10, 11, 12]],
                  [[13, 14, 15], [16, 17, 18]]])

# Extract a specific 2D matrix
print(arr3d[1, :, :])

# Extract a single row across all 2D matrices
print(arr3d[:, 0, :])

# Extract a single element
print(arr3d[2, 1, 2])

# Extract last column across all matrices
print(arr3d[:, :, -1])


[[ 7  8  9]
 [10 11 12]]
[[ 1  2  3]
 [ 7  8  9]
 [13 14 15]]
18
[[ 3  6]
 [ 9 12]
 [15 18]]


In [13]:
#random initialization
arr8= np.random.randint(1,5,9)
arr8 #1D array

array([1, 4, 3, 4, 3, 1, 2, 2, 4], dtype=int32)

In [ ]:
# Creating 2D array using random
arr9= np.random.randint(1,5,(3,4))
arr9

array([[1, 2, 4, 4],
       [4, 1, 4, 4],
       [2, 2, 4, 3]], dtype=int32)

In [ ]:
# Creating array using random()
a= np.random.random(10) # Creates a 1D array of 10 random float values between 0 and 1
a

array([0.00304272, 0.5569442 , 0.24658629, 0.03678068, 0.01917661,
       0.79553288, 0.73065724, 0.03446279, 0.60030139, 0.61836591])

In [ ]:
# Creates a 10x5 matrix with random float values between 0 and 1
b= np.random.random((10,5))
b

array([[0.00149029, 0.75529536, 0.24954362, 0.14264442, 0.14830886],
       [0.20141729, 0.37530204, 0.07509211, 0.54549659, 0.8607642 ],
       [0.5073126 , 0.25042024, 0.92894165, 0.71624547, 0.31541084],
       [0.84516093, 0.95656484, 0.5073886 , 0.88571651, 0.55169225],
       [0.07653576, 0.33779884, 0.85242582, 0.74600877, 0.0137824 ],
       [0.83577827, 0.81856562, 0.96132919, 0.3169075 , 0.39366339],
       [0.53153215, 0.27321054, 0.91847494, 0.42869239, 0.95310982],
       [0.53867648, 0.67643771, 0.64791995, 0.86115969, 0.66166767],
       [0.31162845, 0.30023952, 0.62100694, 0.95071132, 0.0955591 ],
       [0.70355241, 0.8943132 , 0.67055321, 0.81094573, 0.11055545]])

In [ ]:
# Creates a 12x5 matrix with values from 0 to 59 in sequence
arr= np.arange(60).reshape(12,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [ ]:
#Check the shape of array rows and columns
arr.shape

(12, 5)

In [ ]:
#checks the data type of array
arr.dtype

dtype('int64')

In [ ]:
# Return the Dimension of array
arr.ndim

2

In [ ]:
# returns the size of array
arr.size

60

In [ ]:
# Converting into 1d array
arr.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [ ]:
# Converting into 1d array
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [ ]:
# Creates a 2D list (matrix) with 2 rows and 3 columns
lst= [[1,2,3],[4,5,6]]
lst

[[1, 2, 3], [4, 5, 6]]

In [ ]:
#Converting the 2d list into 2d array
arr= np.array(lst)
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
# Returns the shape of array with rows and columns
arr.shape

(2, 3)

In [ ]:
#Transpose the array
arr.T.shape

(3, 2)

In [ ]:
# Creates a 3D NumPy array of shape (5, 15, 3) with values from 0 to 224
arr= np.array(np.arange(225).reshape(5,15,3))

arr

array([[[  0,   1,   2],
        [  3,   4,   5],
        [  6,   7,   8],
        [  9,  10,  11],
        [ 12,  13,  14],
        [ 15,  16,  17],
        [ 18,  19,  20],
        [ 21,  22,  23],
        [ 24,  25,  26],
        [ 27,  28,  29],
        [ 30,  31,  32],
        [ 33,  34,  35],
        [ 36,  37,  38],
        [ 39,  40,  41],
        [ 42,  43,  44]],

       [[ 45,  46,  47],
        [ 48,  49,  50],
        [ 51,  52,  53],
        [ 54,  55,  56],
        [ 57,  58,  59],
        [ 60,  61,  62],
        [ 63,  64,  65],
        [ 66,  67,  68],
        [ 69,  70,  71],
        [ 72,  73,  74],
        [ 75,  76,  77],
        [ 78,  79,  80],
        [ 81,  82,  83],
        [ 84,  85,  86],
        [ 87,  88,  89]],

       [[ 90,  91,  92],
        [ 93,  94,  95],
        [ 96,  97,  98],
        [ 99, 100, 101],
        [102, 103, 104],
        [105, 106, 107],
        [108, 109, 110],
        [111, 112, 113],
        [114, 115, 116],
        [117, 118, 11

In [64]:
#Accessing elements from 3D array

arr= np.array(np.arange(225).reshape(5,15,3))
print(arr[2, 4, 1])  # Access element from 3rd block (index 2), 5th row (index 4), 2nd column (index 1)
print(arr[1, 3, :])  # Entire row 4 (index 3) from block 2 (index 1)
print(arr[:, 5, 2])  # All elements from column 3 (index 2) of row 6 (index 5) across all blocks
print(arr[3, :, :])  # All rows & columns from block 4 (index 3)
print(arr[:, 10, 1])  # All values from row 11 (index 10), column 2 (index 1) across all blocks
print(arr[2, 1:5, :])  # Extract rows 2 to 5 (index 1:5) from block 3 (index 2)
print(arr[1:4, 5:10, 1:3])  # Get Blocks 1 to 4, Rows 5 to 10, Columns 2 to 3


103
[54 55 56]
[ 17  62 107 152 197]
[[135 136 137]
 [138 139 140]
 [141 142 143]
 [144 145 146]
 [147 148 149]
 [150 151 152]
 [153 154 155]
 [156 157 158]
 [159 160 161]
 [162 163 164]
 [165 166 167]
 [168 169 170]
 [171 172 173]
 [174 175 176]
 [177 178 179]]
[ 31  76 121 166 211]
[[ 93  94  95]
 [ 96  97  98]
 [ 99 100 101]
 [102 103 104]]
[[[ 61  62]
  [ 64  65]
  [ 67  68]
  [ 70  71]
  [ 73  74]]

 [[106 107]
  [109 110]
  [112 113]
  [115 116]
  [118 119]]

 [[151 152]
  [154 155]
  [157 158]
  [160 161]
  [163 164]]]


In [ ]:
# Data types -i, f, S, b
# Creates a NumPy array with string (byte) data type ('S' stands for byte string)
arr= np.array([1,2,3,4,5,6], dtype="S")
print(arr.dtype)

|S1


In [ ]:
# String data type array
arr=np.array(['Apple','b','c'])
arr.dtype

dtype('<U5')

In [42]:
# copy and view 
arr=np.array ([1,2,3,4,5])
newarr= arr.copy() # Creates a copy of the 'arr' array, ensuring changes in 'newarr' do not affect 'arr'
arr[0]=14
print(arr)
print(newarr)

[14  2  3  4  5]
[1 2 3 4 5]


In [43]:
arr= np.array([1,2,3,4,5])
newview= arr.view()
print(newview)
print(arr)


[1 2 3 4 5]
[1 2 3 4 5]


In [ ]:
# iterating the array in for loop
arr=np.array([[1,2,3,4],[2,5,7,8]])
for x in arr:
    print(x)

[1 2 3 4]
[2 5 7 8]


In [ ]:
# Changes the 1d array into 4d array using ndmin
arr= np.array([1,2,3,4,5,6,7,8], ndmin=4)
print(arr)
print(arr.ndim)

[[[[1 2 3 4 5 6 7 8]]]]
4


In [ ]:
#Concatenation in array

a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
c= np.concatenate((a, b))
c

array([1, 2, 3, 4, 5, 6, 7, 8])

In [47]:
#Concatenate 2D array
# axis → Specifies the axis along which concatenation should happen.
# axis=0 → Concatenates along rows (vertically).
# axis=1 → Concatenates along columns (horizontally).
a= np.array([[1,2],[3,4]])
b= np.array([[5,6],[7,8]])
c= np.concatenate((a,b),axis=1)
d= np.concatenate((a,b),axis=0)
print("Axis=1 : ")
print(c)
print("Axis = 0 : ")
print(d)

Axis=1 : 
[[1 2 5 6]
 [3 4 7 8]]
Axis = 0 : 
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [53]:
# np.stack() function is used to join multiple arrays along a new axis.
#np.stack(arrays, axis=axis_number)

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

c = np.stack((a, b), axis=0)  # Stacking along axis 0
print(c)

#Stacking Along Axis 1 (Column-Wise)
d = np.stack((a, b), axis=1)  # Stacking along axis 1
print(d)




[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


In [54]:
# Stacking 2D Arrays Along a New Axis
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8]])

z = np.stack((x, y), axis=2) #it creates a new third dimension
print(z)


[[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]


In [ ]:
# np.vstack() → Stacks arrays vertically (row-wise)
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

c = np.vstack((a, b))
print(c)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [49]:
# np.hstack() → Stacks arrays horizontally (column-wise)
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

c = np.hstack((a, b))
print(c)

[[1 2 5 6]
 [3 4 7 8]]


In [50]:
# np.dstack() → Stacks arrays along the third dimension (depth-wise)
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

c = np.dstack((a, b))
print(c)


[[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]


In [51]:
# np.column_stack() → Stacks 1D arrays as columns
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

c = np.column_stack((a, b))
print(c)

[[1 4]
 [2 5]
 [3 6]]


In [66]:
#Replacing 100 with 500 in a 3D NumPy Array
arr = np.array([[[1, 2, 3], [4, 5, 100]], [[7, 8, 9], [10, 11, 12]]])
arr[arr == 100] = 500
print(arr)

[[[  1   2   3]
  [  4   5 500]]

 [[  7   8   9]
  [ 10  11  12]]]


In [67]:

# Creating a 3D array with values from 0 to 224
arr = np.array(np.arange(225).reshape(5, 15, 3))

# Reverse printing all elements
print(arr[::-1, ::-1, ::-1])


[[[224 223 222]
  [221 220 219]
  [218 217 216]
  [215 214 213]
  [212 211 210]
  [209 208 207]
  [206 205 204]
  [203 202 201]
  [200 199 198]
  [197 196 195]
  [194 193 192]
  [191 190 189]
  [188 187 186]
  [185 184 183]
  [182 181 180]]

 [[179 178 177]
  [176 175 174]
  [173 172 171]
  [170 169 168]
  [167 166 165]
  [164 163 162]
  [161 160 159]
  [158 157 156]
  [155 154 153]
  [152 151 150]
  [149 148 147]
  [146 145 144]
  [143 142 141]
  [140 139 138]
  [137 136 135]]

 [[134 133 132]
  [131 130 129]
  [128 127 126]
  [125 124 123]
  [122 121 120]
  [119 118 117]
  [116 115 114]
  [113 112 111]
  [110 109 108]
  [107 106 105]
  [104 103 102]
  [101 100  99]
  [ 98  97  96]
  [ 95  94  93]
  [ 92  91  90]]

 [[ 89  88  87]
  [ 86  85  84]
  [ 83  82  81]
  [ 80  79  78]
  [ 77  76  75]
  [ 74  73  72]
  [ 71  70  69]
  [ 68  67  66]
  [ 65  64  63]
  [ 62  61  60]
  [ 59  58  57]
  [ 56  55  54]
  [ 53  52  51]
  [ 50  49  48]
  [ 47  46  45]]

 [[ 44  43  42]
  [ 41  40  39]


In [68]:
# Flatten the array and reverse it
print(arr.flatten()[::-1])

[224 223 222 221 220 219 218 217 216 215 214 213 212 211 210 209 208 207
 206 205 204 203 202 201 200 199 198 197 196 195 194 193 192 191 190 189
 188 187 186 185 184 183 182 181 180 179 178 177 176 175 174 173 172 171
 170 169 168 167 166 165 164 163 162 161 160 159 158 157 156 155 154 153
 152 151 150 149 148 147 146 145 144 143 142 141 140 139 138 137 136 135
 134 133 132 131 130 129 128 127 126 125 124 123 122 121 120 119 118 117
 116 115 114 113 112 111 110 109 108 107 106 105 104 103 102 101 100  99
  98  97  96  95  94  93  92  91  90  89  88  87  86  85  84  83  82  81
  80  79  78  77  76  75  74  73  72  71  70  69  68  67  66  65  64  63
  62  61  60  59  58  57  56  55  54  53  52  51  50  49  48  47  46  45
  44  43  42  41  40  39  38  37  36  35  34  33  32  31  30  29  28  27
  26  25  24  23  22  21  20  19  18  17  16  15  14  13  12  11  10   9
   8   7   6   5   4   3   2   1   0]


In [69]:
arr[0][::-1]
# only row sequence has reversed

array([[42, 43, 44],
       [39, 40, 41],
       [36, 37, 38],
       [33, 34, 35],
       [30, 31, 32],
       [27, 28, 29],
       [24, 25, 26],
       [21, 22, 23],
       [18, 19, 20],
       [15, 16, 17],
       [12, 13, 14],
       [ 9, 10, 11],
       [ 6,  7,  8],
       [ 3,  4,  5],
       [ 0,  1,  2]])

In [70]:
arr[0][::-1,::-1]
# row and columns both are reversed

array([[44, 43, 42],
       [41, 40, 39],
       [38, 37, 36],
       [35, 34, 33],
       [32, 31, 30],
       [29, 28, 27],
       [26, 25, 24],
       [23, 22, 21],
       [20, 19, 18],
       [17, 16, 15],
       [14, 13, 12],
       [11, 10,  9],
       [ 8,  7,  6],
       [ 5,  4,  3],
       [ 2,  1,  0]])

In [72]:
arr[0] = arr[0][::-1,::-1]
# first table elements has been replaced with reversed elements
arr[0]

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29],
       [30, 31, 32],
       [33, 34, 35],
       [36, 37, 38],
       [39, 40, 41],
       [42, 43, 44]])

In [73]:
# commonly used function of Numpy array

arr = np.arange(60).reshape(15,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31],
       [32, 33, 34, 35],
       [36, 37, 38, 39],
       [40, 41, 42, 43],
       [44, 45, 46, 47],
       [48, 49, 50, 51],
       [52, 53, 54, 55],
       [56, 57, 58, 59]])

In [ ]:
print(np.min(arr))
print(np.max(arr))
print(np.mean(arr))
print(np.sum(arr))
print(np.var(arr)) # Measure variance
print(np.std(arr)) # Measure standard deviation
# same as min , max , mean ,sum , var , std

0
59
29.5
1770
299.9166666666667
17.318102282486574


In [82]:
# SPLITTING THE NUMPY ARRAY
# array_split() for splitting arrays, we pass it the array we want to split and the number of splits.
arr = np.array([1,2,3,4,5,6])
newarr = np.array_split(arr, 3)
print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [84]:
# Splitting array in 4 parts:
arr= np.array([1,2,3,4,5,6])
newarr = np.array_split(arr, 4)
print(newarr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


In [85]:
# Access teh splitted array
newarr = np.array_split(arr, 3 )
print(newarr[0])
print(newarr[1])
print(newarr[2])

[1 2]
[3 4]
[5 6]


In [86]:
# splitting the 2D array
arr =np.array([[1,2],[3,4],[5,6],[7,8],[9,10],[11,12]])
newarr = np.array_split(arr, 3)
newarr

[array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]]),
 array([[ 9, 10],
        [11, 12]])]

In [95]:
# Splitting methods - hsplit, vsplit
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
b= np.hsplit(a, 3)
print(b)
# Splitting 2D array horizontally   


[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [96]:
# Splitting 2D array vertically
c= np.vsplit(a, 3)
print(c)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]


In [97]:
#Numpy Searching Array
arr= np.array([1,2,3,4,5,4,4])
x = np.where(arr == 4)
print(x)


(array([3, 5, 6]),)


In [98]:
# Find the indexes where the values are even:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
x = np.where(arr%2 == 0)
print(x)

(array([1, 3, 5, 7]),)


In [99]:
# Find the indexes where the values are odd:
arr = np.array([1,2,3,4,5,6,7,8])
x= np.where (arr%2 == 1)
print(x)


(array([0, 2, 4, 6]),)


In [100]:
# Search Sorted
arr = np.array([6,7,8,9])
x = np.searchsorted(arr, 7)
print(x)

1


In [101]:
# searchsorted right side
arr = np.array([6,7,8,9])
x = np.searchsorted(arr, 7, side='right')
print(x)

2


[1 2 3]


In [ ]:
# SORTING THE NUMPY ARRAY USING sort()
arr = np.array([3,2,0,1])
print(np.sort(arr))

[0 1 2 3]


In [104]:
# sort boolean array
arr = np.array([True, False, True])
print(np.sort(arr))

[False  True  True]


In [105]:
# Sorting 2d Array
arr = np.array([[3,2,4],[5,0,1]])
print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


In [106]:
# FILTER NUMPY ARRAY
a = np.array([1,2,3,4,5])
x= [True, False, True, False, False]
newarr = a[x]
print(newarr)

[1 3]


In [108]:
# Create a filter array that will return only values higher than 14:
arr = np.array([1,42,52,74,56,2,12,36,31,11,10,5,6,4,])
filter_arr =[]
for element in arr:
    if element > 14:
        filter_arr.append(True)
    else:
        filter_arr.append(False)
        
new = arr[filter_arr]
print(filter_arr)
print(new)


[False, True, True, True, True, False, False, True, True, False, False, False, False, False]
[42 52 74 56 36 31]


In [109]:
# Create a filter array that will return only even elements from the original array:

arr = np.array([1, 2, 3, 4, 5, 6, 7])
filter_arr = []
for element in arr:
    if element % 2 == 0:
        filter_arr.append(True)
    else:
        filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False, True, False, True, False, True, False]
[2 4 6]


In [110]:
# Creating Filter Directly From Array
arr = np.array([41, 42, 43, 44])

filter_arr = arr > 42

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False False  True  True]
[43 44]
